### ISSUE TITLE
Fix ingress url propagation

### ISSUE THREAD

**Issue by michaeldmitry** [canonical/parca-k8s-operator#372]
### Bug Description

When `parca-k8s` is behind an ingress (traefik), it doesn't propagate its ingress url over `parca-store-endpoint` relation. It's missing an argument to `external_url`.

### To Reproduce

1. Deploy Traefik and Parca in k8s model and relate them
2. Deploy Parca agent in a machine model
3. CMR parca with parca agent
4. jhack show-relation parca parca-agent 
5. You'll see the unit's url instead of the ingress url

### Environment

juju 3.6.1
microk8s v1.28.15

### Relevant log output

```shell
N/A
```

**Comment by PietroPasotti** [comment]
todo: try and reproduce after #391 merges (reconciler approach should fix this kind of issues)

**Comment by michaeldmitry** [comment]
> todo: try and reproduce after [#391](https://github.com/canonical/parca-k8s-operator/pull/391) merges (reconciler approach should fix this kind of issues)

Even after the latest reconcile changes, the issue persists.
Seems we're missing sth like `parca_store_endpoint.update_source()`
